FROM python:3.7.7-slim

RUN pip install gdown==3.10.3

COPY src/ /heetch-test/src/

WORKDIR /heetch-test
ENV PYTHONPATH /heetch-test

RUN ["chmod", "+x", "src/data-setup/download_data_raw.sh"]
CMD ["/bin/bash", "src/data-setup/download_data_raw.sh"]