#FROM amancevice/pandas:1.0.3-slim
FROM jupyter/scipy-notebook:29f53f8b9927

RUN pip install tqdm==4.31.1
RUN pip install xgboost==0.82
RUN pip install tqdm==4.36.1
RUN pip install shap==0.28.5
RUN pip install logmatic-python==0.1.7

RUN pip install graphene==2.1.3
RUN pip install streamlit==0.51.0
RUN pip install bokeh==1.4.0
RUN pip install PyQt5==5.14.1
RUN pip install Flask==1.1.0
RUN pip install Flask-GraphQL==1.4.1
RUN pip install Flask-JWT==0.3.2
RUN pip install Flask-RESTful==0.3.6
RUN pip install imbalanced-learn==0.6.2

COPY src/ /heetch-test/src/

WORKDIR /heetch-test

ENV PYTHONPATH /heetch-test

CMD ["/bin/bash", "sleep 1m"]